"""empty message

Revision ID: 0e68808e92f5
Revises: 6334ac7ca87f
Create Date: 2025-12-10 04:18:30.200824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e68808e92f5'
down_revision: Union[str, None] = '6334ac7ca87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('token', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'token')
    # ### end Alembic commands ###
