"""empty message

Revision ID: 514d2b4afaad
Revises: 8198fde715b3
Create Date: 2025-12-09 23:09:23.915460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '514d2b4afaad'
down_revision: Union[str, None] = '8198fde715b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user_sessions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('user_sessions', 'access_expires_at')
    # ### end Alembic commands ###
